-- Vehicles
-- add any custom vehicles here
-- we dont include motorcycles here, i suggest you not
Config.PercentShellPrice = 0.1
Config.Vehicles = {
    -- LOCAL VEHICLES

	['issi3'] = {
		['name'] = 'Issi Classic',
		['brand'] = 'Weeny',
		['model'] = 'issi3',
		['price'] = 5000,
		['category'] = 'compacts',
		['hash'] = `issi3`,
		['shop'] = 'pdm',
	},
	['gauntlet5'] = {
		['name'] = 'Gauntlet Classic Custom',
		['brand'] = 'Bravado',
		['model'] = 'gauntlet5',
		['price'] = 120000,
		['category'] = 'muscle',
		['hash'] = `gauntlet5`,
		['shop'] = 'pdm',
	},
	['virgo2'] = {
		['name'] = 'Virgo Classic',
		['brand'] = 'Dundreary',
		['model'] = 'virgo2',
		['price'] = 21000,
		['category'] = 'muscle',
		['hash'] = `virgo2`,
		['shop'] = 'pdm',
	},
	['virgo3'] = {
		['name'] = 'Virgo Custom Classic',
		['brand'] = 'Dundreary',
		['model'] = 'virgo3',
		['price'] = 21000,
		['category'] = 'muscle',
		['hash'] = `virgo3`,
		['shop'] = 'pdm',
	},
	['coquette2'] = {
		['name'] = 'Coquette Classic',
		['brand'] = 'Invetero',
		['model'] = 'coquette2',
		['price'] = 165000,
		['category'] = 'sportclass',
		['hash'] = `coquette2`,
		['shop'] = 'pdm',
	},
	['jester3'] = {
		['name'] = 'Jester Classic',
		['brand'] = 'Dinka',
		['model'] = 'jester3',
		['price'] = 85000,
		['category'] = 'sports',
		['hash'] = `jester3`,
		['shop'] = 'pdm',
	},
	['sentinel3'] = {
		['name'] = 'Sentinel Classic',
		['brand'] = 'Übermacht',
		['model'] = 'sentinel3',
		['price'] = 70000,
		['category'] = 'coupes',
		['hash'] = `sentinel3`,
		['shop'] = 'pdm',
	},
	['sultan2'] = {
		['name'] = 'Sultan Classic',
		['brand'] = 'Karin',
		['model'] = 'sultan2',
		['price'] = 55000,
		['category'] = 'sports',
		['hash'] = `sultan2`,
		['shop'] = 'pdm',
	},
	['sultan3'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Sultan RS Classic',
		['brand'] = 'Karin',
		['model'] = 'sultan3',
		['price'] = 56000,
		['category'] = 'sports',
		['hash'] = `sultan3`,
		['shop'] = 'pdm',
	},
	['cheetah2'] = {
		['name'] = 'Cheetah Classic',
		['brand'] = 'Grotti',
		['model'] = 'cheetah2',
		['price'] = 195000,
		['category'] = 'sportclass',
		['hash'] = `cheetah2`,
		['shop'] = 'pdm',
	},
	['infernus2'] = {
		['name'] = 'Infernus Classic',
		['brand'] = 'Pegassi',
		['model'] = 'infernus2',
		['price'] = 245000,
		['category'] = 'sportclass',
		['hash'] = `infernus2`,
		['shop'] = 'pdm',
	},
	['turismo2'] = {
		['name'] = 'Turismo Classic',
		['brand'] = 'Grotti',
		['model'] = 'turismo2',
		['price'] = 170000,
		['category'] = 'sportclass',
		['hash'] = `turismo2`,
		['shop'] = 'pdm',
	},
	['zion3'] = {							--DLC
		['name'] = 'Zion Classic',
		['brand'] = 'Übermacht',
		['model'] = 'zion3',
		['price'] = 45000,
		['category'] = 'sportclass',
		['hash'] = `zion3`,
		['shop'] = 'pdm',
	},
	['youga3'] = {
		['name'] = 'Youga Classic 4x4',
		['brand'] = 'Bravado',
		['model'] = 'youga3',
		['price'] = 15000,
		['category'] = 'vans',
		['hash'] = `youga3`,
		['shop'] = 'pdm',
	},
	['youga'] = {
		['name'] = 'Youga',
		['brand'] = 'Bravado',
		['model'] = 'youga',
		['price'] = 8000,
		['category'] = 'vans',
		['hash'] = `youga`,
		['shop'] = 'pdm',
	},
	['youga2'] = {
		['name'] = 'Youga Classic',
		['brand'] = 'Bravado',
		['model'] = 'youga2',
		['price'] = 14500,
		['category'] = 'vans',
		['hash'] = `youga2`,
		['shop'] = 'pdm',
	},

	---DONOR
	['cc4'] = {
		['name'] = 'Vette-69',
		['brand'] = 'Chevy',
		['model'] = 'cc4',
		['price'] = 5000000,
		['category'] = 'imuscle',
		['hash'] = `cc4`,
		['shop'] = 'pdm',
	},
	['gmcs'] = {
		['name'] = 'Sierra-18',
		['brand'] = 'GMC',
		['model'] = 'gmcs',
		['price'] = 7500000,
		['category'] = 'itruck',
		['hash'] = `gmcs`,
		['shop'] = 'pdm',
	},
	['bcal450'] = {
		['name'] = 'F-350-lift',
		['brand'] = 'Ford',
		['model'] = 'bcal450',
		['price'] = 7500000,
		['category'] = 'itruck',
		['hash'] = `bcal450`,
		['shop'] = 'pdm',
	},
	['bcps'] = {
		['name'] = 'Chiron-PS',
		['brand'] = 'Bugatti',
		['model'] = 'bcps',
		['price'] = 10000000,
		['category'] = 'isuper',
		['hash'] = `bcps`,
		['shop'] = 'pdm',
	},
}