Config = {}

Config.objects = {
	object = nil, ObjectVertX = nil, ObjectVertY = nil, ObjectVertZ = nil, OjbectDir = nil, isBed = nil,
	SitAnimation = 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER',
	LayBackAnimation = 'WORLD_HUMAN_SUNBATHE_BACK',
	LayStomachAnimation = 'WORLD_HUMAN_SUNBATHE',
	locations = {
		[1] = {object="v_med_bed2", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-1.4, direction=0.0, bed=true},
		[2] = {object="v_serv_ct_chair02", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.0, direction=168.0, bed=false},
		[3] = {object="prop_off_chair_04", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=168.0, bed=false},
		[4] = {object="prop_off_chair_03", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=168.0, bed=false},
		[5] = {object="prop_off_chair_05", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=168.0, bed=false},
		[6] = {object="v_club_officechair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=168.0, bed=false},
		[7] = {object="v_ilev_leath_chr", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=168.0, bed=false},
		[8] = {object="v_corp_offchair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=168.0, bed=false},
		[9] = {object="v_med_emptybed", verticalOffsetX=0.0, verticalOffsetY=0.13, verticalOffsetZ=-0.2, direction=90.0, bed=false},
		[10] = {object="Prop_Off_Chair_01", verticalOffsetX=0.0, verticalOffsetY=-0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false},
		[11] = {object="v_ilev_m_dinechair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=168.0, bed=false},
		[12] = {object="prop_off_chair_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=168.0, bed=false},
		[13] = {object="prop_chair_04a", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
		[14] = {object="hei_prop_heist_off_chair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
		[15] = {object="v_ret_gc_chair03", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=0.2, direction=180.16, bed=false},
		[16] = {object="ex_prop_offchair_exec_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=0.2, direction=180.16, bed=false},
		[17] = {object="v_ret_chair_white", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
		[18] = {object="v_ret_chair", verticalOffsetX=0.0, verticalOffsetY=0.2, verticalOffsetZ=-0.6, direction=180.16, bed=false},
		[19] = {object="ex_prop_offchair_exec_04", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.2, direction=180.16, bed=false},
		[20] = {object="v_ret_gc_chair03", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
		[21] = {object="p_clb_officechair_s", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
		[22] = {object="p_armchair_01_s", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
		[23] = {object="p_dinechair_01_s", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
		[24] = {object="apa_mp_h_yacht_armchair_03", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
		[25] = {object="apa_mp_h_yacht_strip_chair_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
		[26] = {object="v_ret_gc_chair03", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
		[27] = {object="p_clb_officechair_s", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
		[28] = {object="v_res_m_l_chair1", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
		[29] = {object="apa_mp_h_stn_chairstrip_05", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
		[30] = {object="v_res_m_l_chair1", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
		[31] = {object="v_res_m_l_chair1", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
		[32] = {object="prop_sol_chair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
		[33] = {object="apa_mp_h_stn_chairarm_11", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
		[34] = {object="v_corp_bk_chair2", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
		[35] = {object="bkr_prop_biker_boardchair01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
		[36] = {object="prop_chair_01a", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
		[36] = {object="bkr_prop_biker_boardchair01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
		--pillbox
		[37] = {object="gabz_pillbox_MRI_bed", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-2.0, direction=0.0, bed=true},
		[38] = {object="gabz_pillbox_diagnostics_bed_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-2.0, direction=0.0, bed=true},
		[39] = {object="gabz_pillbox_diagnostics_bed_02", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-2.0, direction=0.0, bed=true},
		[40] = {object="gabz_pillbox_diagnostics_bed_03", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-2.0, direction=0.0, bed=true},
		--resturant
		[41] = {object="v_res_fa_chair01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.2, direction=180.16, bed=false},
		[42] = {object="v_ret_gc_chair01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.2, direction=180.16, bed=false},
		[43] = {object="v_res_m_dinechair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.2, direction=180.16, bed=false},
		[44] = {object="v_res_d_armchair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.2, direction=180.16, bed=false},
		[45] = {object="prop_sol_chair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.2, direction=180.16, bed=false},
		[46] = {object="prop_sol_chair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.2, direction=180.16, bed=false},
		--dmv
		[47] = {object="ex_prop_offchair_exec_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
		[48] = {object="v_corp_bk_chair1", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
		[49] = {object="bkr_prop_biker_boardchair01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
		[50] = {object="v_ilev_chair02_ped", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
		[52] = {object="prop_cs_office_chair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
		[53] = {object="ba_prop_battle_club_chair_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
		[54] = {object="ba_prop_battle_club_chair_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.16, bed=false},
	}
}